#!/usr/bin/env python
import argparse
import fileinput


def count_line(input_line):
    return 1


def count_words(input_line):
    return len(input_line.split())


def count_bytes(input_line):
    return len(input_line.encode('utf-8'))


def count_all(finput):
    lines_total, words_total, chunks_total = 0, 0, 0
    for input_line in finput:
        lines_total += count_line(input_line)
        words_total += count_words(input_line)
        chunks_total += count_bytes(input_line)
    return map(str, (lines_total, words_total, chunks_total))


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-l', '--lines', help='Посчитает количество строк.', action='store_true')
    parser.add_argument('-w', '--words', help='Посчитает количество слов.', action='store_true')
    parser.add_argument('-c', '--chunks', help='Посчитает количество байт.', action='store_true')
    parser.add_argument('files', metavar='FILE', nargs='*', help='Eсли файлы не переданы в качестве аргумента, то считывать из stdin.')
    args = parser.parse_args()

    with fileinput.input(files=args.files) as finput:
        if args.lines:
            res = sum((count_line(line) for line in finput))
        elif args.words:
            res = sum((count_words(line) for line in finput))
        elif args.chunks:
            res = sum((count_bytes(line) for line in finput))
        else:
            res = ' '.join(count_all(finput))

    print(res)
